/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\myLearnSpace\\AndMeLearnProtal\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-0963fc52",
    path: "/CSSDoc/01css%E5%B1%9E%E6%80%A7.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0963fc52").then(next)
    },
  },
  {
    path: "/CSSDoc/01css属性.html",
    redirect: "/CSSDoc/01css%E5%B1%9E%E6%80%A7.html"
  },
  {
    path: "/CSSDoc/01css属性.html",
    redirect: "/CSSDoc/01css%E5%B1%9E%E6%80%A7.html"
  },
  {
    name: "v-97020208",
    path: "/HTMLDoc/02%E6%A1%88%E4%BE%8B%E5%92%8C%E6%96%B9%E6%A1%88.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-97020208").then(next)
    },
  },
  {
    path: "/HTMLDoc/02案例和方案.html",
    redirect: "/HTMLDoc/02%E6%A1%88%E4%BE%8B%E5%92%8C%E6%96%B9%E6%A1%88.html"
  },
  {
    path: "/HTMLDoc/02案例和方案.html",
    redirect: "/HTMLDoc/02%E6%A1%88%E4%BE%8B%E5%92%8C%E6%96%B9%E6%A1%88.html"
  },
  {
    name: "v-02d5a4ac",
    path: "/CSSDoc/02%E6%A1%88%E4%BE%8B%E5%92%8C%E6%96%B9%E6%A1%88.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-02d5a4ac").then(next)
    },
  },
  {
    path: "/CSSDoc/02案例和方案.html",
    redirect: "/CSSDoc/02%E6%A1%88%E4%BE%8B%E5%92%8C%E6%96%B9%E6%A1%88.html"
  },
  {
    path: "/CSSDoc/02案例和方案.html",
    redirect: "/CSSDoc/02%E6%A1%88%E4%BE%8B%E5%92%8C%E6%96%B9%E6%A1%88.html"
  },
  {
    name: "v-f88cb4a8",
    path: "/HTMLDoc/01%E5%9F%BA%E7%A1%80%E6%A0%87%E7%AD%BE.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f88cb4a8").then(next)
    },
  },
  {
    path: "/HTMLDoc/01基础标签.html",
    redirect: "/HTMLDoc/01%E5%9F%BA%E7%A1%80%E6%A0%87%E7%AD%BE.html"
  },
  {
    path: "/HTMLDoc/01基础标签.html",
    redirect: "/HTMLDoc/01%E5%9F%BA%E7%A1%80%E6%A0%87%E7%AD%BE.html"
  },
  {
    name: "v-07b30954",
    path: "/JavaScript/01Javascript%E5%9F%BA%E7%A1%80.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-07b30954").then(next)
    },
  },
  {
    path: "/JavaScript/01Javascript基础.html",
    redirect: "/JavaScript/01Javascript%E5%9F%BA%E7%A1%80.html"
  },
  {
    path: "/JavaScript/01Javascript基础.html",
    redirect: "/JavaScript/01Javascript%E5%9F%BA%E7%A1%80.html"
  },
  {
    name: "v-b9d8863c",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b9d8863c").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-3ec73ea0",
    path: "/JavaScript/02JavascriptES6%20%E8%AF%AD%E6%B3%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3ec73ea0").then(next)
    },
  },
  {
    path: "/JavaScript/02JavascriptES6 语法.html",
    redirect: "/JavaScript/02JavascriptES6%20%E8%AF%AD%E6%B3%95.html"
  },
  {
    path: "/JavaScript/02JavascriptES6 语法.html",
    redirect: "/JavaScript/02JavascriptES6%20%E8%AF%AD%E6%B3%95.html"
  },
  {
    name: "v-7202a8c2",
    path: "/JavaScript/03JavaScript%E5%85%AB%E8%82%A1%E6%96%87.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7202a8c2").then(next)
    },
  },
  {
    path: "/JavaScript/03JavaScript八股文.html",
    redirect: "/JavaScript/03JavaScript%E5%85%AB%E8%82%A1%E6%96%87.html"
  },
  {
    path: "/JavaScript/03JavaScript八股文.html",
    redirect: "/JavaScript/03JavaScript%E5%85%AB%E8%82%A1%E6%96%87.html"
  },
  {
    name: "v-5fb50f78",
    path: "/Vue/01%E6%B5%85%E5%85%A5Vue2x.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5fb50f78").then(next)
    },
  },
  {
    path: "/Vue/01浅入Vue2x.html",
    redirect: "/Vue/01%E6%B5%85%E5%85%A5Vue2x.html"
  },
  {
    path: "/Vue/01浅入Vue2x.html",
    redirect: "/Vue/01%E6%B5%85%E5%85%A5Vue2x.html"
  },
  {
    name: "v-12d4c123",
    path: "/JavaScript/04Js%E5%B8%B8%E8%A7%81%E9%9D%A2%E8%AF%95%E9%A2%98.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-12d4c123").then(next)
    },
  },
  {
    path: "/JavaScript/04Js常见面试题.html",
    redirect: "/JavaScript/04Js%E5%B8%B8%E8%A7%81%E9%9D%A2%E8%AF%95%E9%A2%98.html"
  },
  {
    path: "/JavaScript/04Js常见面试题.html",
    redirect: "/JavaScript/04Js%E5%B8%B8%E8%A7%81%E9%9D%A2%E8%AF%95%E9%A2%98.html"
  },
  {
    name: "v-294517a1",
    path: "/Vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-294517a1").then(next)
    },
  },
  {
    path: "/Vue/index.html",
    redirect: "/Vue/"
  },
  {
    name: "v-3460a8ac",
    path: "/fontend/test1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3460a8ac").then(next)
    },
  },
  {
    name: "v-67562457",
    path: "/Vue/02Vue%E7%9A%84%E5%85%A8%E5%AE%B6%E6%A1%B6.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-67562457").then(next)
    },
  },
  {
    path: "/Vue/02Vue的全家桶.html",
    redirect: "/Vue/02Vue%E7%9A%84%E5%85%A8%E5%AE%B6%E6%A1%B6.html"
  },
  {
    path: "/Vue/02Vue的全家桶.html",
    redirect: "/Vue/02Vue%E7%9A%84%E5%85%A8%E5%AE%B6%E6%A1%B6.html"
  },
  {
    name: "v-ff71cae8",
    path: "/fontend/test2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ff71cae8").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]