/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "AndMeBlockDocs",
  "description": "我的个人学习笔记",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/logo.png"
      }
    ]
  ],
  "pages": [
    {
      "title": "常见属性",
      "frontmatter": {},
      "regularPath": "/CSSDoc/01css%E5%B1%9E%E6%80%A7.html",
      "relativePath": "CSSDoc/01css属性.md",
      "key": "v-0963fc52",
      "path": "/CSSDoc/01css%E5%B1%9E%E6%80%A7.html"
    },
    {
      "title": "案例和方案",
      "frontmatter": {},
      "regularPath": "/HTMLDoc/02%E6%A1%88%E4%BE%8B%E5%92%8C%E6%96%B9%E6%A1%88.html",
      "relativePath": "HTMLDoc/02案例和方案.md",
      "key": "v-97020208",
      "path": "/HTMLDoc/02%E6%A1%88%E4%BE%8B%E5%92%8C%E6%96%B9%E6%A1%88.html"
    },
    {
      "title": "一些案例和方案",
      "frontmatter": {},
      "regularPath": "/CSSDoc/02%E6%A1%88%E4%BE%8B%E5%92%8C%E6%96%B9%E6%A1%88.html",
      "relativePath": "CSSDoc/02案例和方案.md",
      "key": "v-02d5a4ac",
      "path": "/CSSDoc/02%E6%A1%88%E4%BE%8B%E5%92%8C%E6%96%B9%E6%A1%88.html"
    },
    {
      "title": "基础标签",
      "frontmatter": {},
      "regularPath": "/HTMLDoc/01%E5%9F%BA%E7%A1%80%E6%A0%87%E7%AD%BE.html",
      "relativePath": "HTMLDoc/01基础标签.md",
      "key": "v-f88cb4a8",
      "path": "/HTMLDoc/01%E5%9F%BA%E7%A1%80%E6%A0%87%E7%AD%BE.html"
    },
    {
      "title": "Javascript基础",
      "frontmatter": {},
      "regularPath": "/JavaScript/01Javascript%E5%9F%BA%E7%A1%80.html",
      "relativePath": "JavaScript/01Javascript基础.md",
      "key": "v-07b30954",
      "path": "/JavaScript/01Javascript%E5%9F%BA%E7%A1%80.html"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/logo.jpg",
        "actionText": "开始阅读 →",
        "actionLink": "/fontend/test1/",
        "features": [
          {
            "title": "记录前端技术",
            "details": "尝试着收录前端小虾米的学习中的各种技术收获"
          },
          {
            "title": "记录各种采坑",
            "details": "写下每次刻骨铭心的采坑和一些高血压瞬间的BUG"
          },
          {
            "title": "努力保持更新",
            "details": "尽力保持更新，争取为自己的技术成长做个见证"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-b9d8863c",
      "path": "/"
    },
    {
      "title": "JavascriptES6 语法",
      "frontmatter": {},
      "regularPath": "/JavaScript/02JavascriptES6%20%E8%AF%AD%E6%B3%95.html",
      "relativePath": "JavaScript/02JavascriptES6 语法.md",
      "key": "v-3ec73ea0",
      "path": "/JavaScript/02JavascriptES6%20%E8%AF%AD%E6%B3%95.html"
    },
    {
      "title": "JavaScript八股文",
      "frontmatter": {},
      "regularPath": "/JavaScript/03JavaScript%E5%85%AB%E8%82%A1%E6%96%87.html",
      "relativePath": "JavaScript/03JavaScript八股文.md",
      "key": "v-7202a8c2",
      "path": "/JavaScript/03JavaScript%E5%85%AB%E8%82%A1%E6%96%87.html"
    },
    {
      "title": "浅入Vue2x",
      "frontmatter": {},
      "regularPath": "/Vue/01%E6%B5%85%E5%85%A5Vue2x.html",
      "relativePath": "Vue/01浅入Vue2x.md",
      "key": "v-5fb50f78",
      "path": "/Vue/01%E6%B5%85%E5%85%A5Vue2x.html"
    },
    {
      "title": "Javascript常见的一些面试题",
      "frontmatter": {},
      "regularPath": "/JavaScript/04Js%E5%B8%B8%E8%A7%81%E9%9D%A2%E8%AF%95%E9%A2%98.html",
      "relativePath": "JavaScript/04Js常见面试题.md",
      "key": "v-12d4c123",
      "path": "/JavaScript/04Js%E5%B8%B8%E8%A7%81%E9%9D%A2%E8%AF%95%E9%A2%98.html"
    },
    {
      "title": "Vue",
      "frontmatter": {},
      "regularPath": "/Vue/",
      "relativePath": "Vue/README.md",
      "key": "v-294517a1",
      "path": "/Vue/",
      "headers": [
        {
          "level": 2,
          "title": "01XXX",
          "slug": "_01xxx"
        },
        {
          "level": 2,
          "title": "02XXX",
          "slug": "_02xxx"
        }
      ]
    },
    {
      "title": "123123",
      "frontmatter": {},
      "regularPath": "/fontend/test1.html",
      "relativePath": "fontend/test1.md",
      "key": "v-3460a8ac",
      "path": "/fontend/test1.html",
      "headers": [
        {
          "level": 3,
          "title": "123",
          "slug": "_123"
        },
        {
          "level": 3,
          "title": "1234",
          "slug": "_1234"
        }
      ]
    },
    {
      "title": "Vue的全家桶",
      "frontmatter": {},
      "regularPath": "/Vue/02Vue%E7%9A%84%E5%85%A8%E5%AE%B6%E6%A1%B6.html",
      "relativePath": "Vue/02Vue的全家桶.md",
      "key": "v-67562457",
      "path": "/Vue/02Vue%E7%9A%84%E5%85%A8%E5%AE%B6%E6%A1%B6.html"
    },
    {
      "title": "asdad",
      "frontmatter": {},
      "regularPath": "/fontend/test2.html",
      "relativePath": "fontend/test2.md",
      "key": "v-ff71cae8",
      "path": "/fontend/test2.html"
    }
  ],
  "themeConfig": {
    "sidebarDepth": 2,
    "lastUpdated": "Last Updated",
    "nav": [
      {
        "text": "不懂就点这",
        "link": "http://www.baidu.com/"
      },
      {
        "text": "Vue",
        "link": "https://cn.vuejs.org/"
      },
      {
        "text": "经典三剑客",
        "items": [
          {
            "text": "JS合集",
            "link": "/JavaScript/01Javascript基础"
          },
          {
            "text": "CSS合集",
            "link": "/CSSDoc/01css属性"
          },
          {
            "text": "HTML合集",
            "link": "/HTMLDoc/01基础标签"
          }
        ]
      },
      {
        "text": "框架经验",
        "items": [
          {
            "text": "Vue",
            "link": "/Vue/"
          }
        ]
      },
      {
        "text": "GitHub",
        "items": [
          {
            "text": "GitHub地址",
            "link": "https://github.com/AndMe0818?tab=repositories"
          }
        ]
      }
    ],
    "sidebar": {
      "/fontend/": [
        {
          "title": "Group 1",
          "collapsable": false,
          "children": [
            {
              "title": "test111",
              "path": "/fontend/test1"
            },
            {
              "title": "test222",
              "path": "/fontend/test2"
            }
          ]
        }
      ],
      "/Vue/": [
        {
          "title": "Vue",
          "collapsable": false,
          "children": [
            {
              "title": "浅入Vue2x",
              "path": "/Vue/01浅入Vue2x"
            },
            {
              "title": "Vue2x全家桶",
              "path": "/Vue/02Vue的全家桶"
            }
          ]
        }
      ],
      "/JavaScript/": [
        {
          "title": "JavaScript",
          "collapsable": false,
          "children": [
            {
              "title": "Javascript基础",
              "path": "/JavaScript/01Javascript基础"
            },
            {
              "title": "ES6语法",
              "path": "/JavaScript/02JavascriptES6 语法"
            },
            {
              "title": "JS八股文",
              "path": "/JavaScript/03JavaScript八股文"
            },
            {
              "title": "常见面试题",
              "path": "/JavaScript/04Js常见面试题"
            }
          ]
        }
      ],
      "/CSSDoc/": [
        {
          "title": "CSS",
          "collapsable": false,
          "children": [
            {
              "title": "css属性",
              "path": "/CSSDoc/01css属性"
            },
            {
              "title": "02案例和方案",
              "path": "/CSSDoc/02案例和方案"
            }
          ]
        }
      ],
      "/HTMLDoc/": [
        {
          "title": "HTML",
          "collapsable": false,
          "children": [
            {
              "title": "基础标签",
              "path": "/HTMLDoc/01基础标签"
            },
            {
              "title": "案例和方案",
              "path": "/HTMLDoc/02案例和方案"
            }
          ]
        }
      ]
    }
  }
}